from django.test import TestCase
from shop.utils import is_valid_receipt

class CryptoTest(TestCase):
    def test_verify_receipt_positive(self):
        # data generated by contract tests
        etherum_address = '0x6c6724Ed55277203d4b21fd25d6aB65eC19B1db3'
        receipt = '0x9fd631dd1afeebf8340bcad79f2d2482b19bf3add633f3773cfda1d43b7546b414e9b0af258d49dcb168e4375334653b266481ae8c3a1fa20fdad6e6174dc25100'
        session_id = '0x3129042299270b945ba819991b82d07285772951e5e99060e044e1eb09cf5f64'
        value = 1
        self.assertTrue(is_valid_receipt(receipt, etherum_address, session_id, value))

    def test_verify_receipt_negative(self):
        etherum_address = '0x6c6724Ed55277203d4b21fd25d6aB65eC19B1db3'
        receipt = '0x9fd631dd1afeebf8340bcad79f2d2482b19bf3add633f3773cfda1d43b7546b414e9b0af258d49dcb168e4375334653b266481ae8c3a1fa20fdad6e6174dc25100'
        # just changed first byte in session_id
        session_id = '0x4129042299270b945ba819991b82d07285772951e5e99060e044e1eb09cf5f64'
        value = 1
        self.assertFalse(is_valid_receipt(receipt, etherum_address, session_id, value))
